# Server settings
host: 0.0.0.0

# Site settings
version: 0.1.0
title: Emptyset Creative
email: projects@emptyset.co
description: Idea builders, not just idea guys.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "/" # the base hostname & protocol for your site
twitter_username: emptysetco
github_username: emptysetco

#basic site variables
paginate: 					5
paginate_path: "posts/page:num"

# Author Settings
authors:
  Bryan:
    name: Bryan Lokey
    display_name: Bryan
    url: BryanLokey.com
    bio: When one loves affirmation and heaven, one is able to absorb volume. As i have avoided you, so you must synthesise one another.
    email: bryan@emptyset.co
    image: //bryanlokey.com/images/about.png
    twitter_url: 					"//twitter.com/bryanlokey"
    github_url:  					"//github.com/brylok"
    linkedin_url:  				"//linkedin.com/in/bryanlokey"
  Jason:
    name: Jason Adkison
    display_name: Jason
    url:  Emptyset.co
    bio:  When one loves affirmation and heaven, one is able to absorb volume. As i have avoided you, so you must synthesise one another.
    email: jason@emptyset.co
    image: //www.mattr.co/uploads/team_media/jason-adkison/jason-2-530e40306e0a9.png
    github_url:  					"//github.com/jasonadkison"
    linkedin_url:  				"//linkedin.com/pub/jason-adkison/8/b6/688"
  Emptyset:
    name: Emptyset Creative
    display_name: Emptyset
    url:  Emptyset.co
    bio:  Emptyset Creative is a group of developers working together to build apps and plugins using the latest in web technology.
    email: projects@emptyset.co
    image: //misanthropology101.files.wordpress.com/2015/01/athiest-empty-set.png
    twitter_url: 					"//twitter.com/emptysetco"
    github_url:  					"//github.com/emptysetco"



# Build settings
markdown: kramdown

collections:
  projects:
    output: true

defaults:
  -
    scope:
      path: "blog"
      type: "posts"
    values:
      layout: "post"
      author: "The Post Man"
  -
    scope:
      path: "projects"
      type: "projects"
    values:
      layout: "project"
      author: "The Project Man"


#
# Plugin: jekyll-assets
#
assets:
  #
  # Pathname of the destination of generated (bundled) assets relative
  # to the destination of the root.
  #
  dirname: assets
  #
  # Base URL of assets paths.
  #
  baseurl: /assets/
  #
  # Pathnames where to find assets relative to the root of the site.
  #
  sources:
    - _assets/javascripts
    - _assets/stylesheets
    - _assets/images
    - _assets/stylesheets/vendor/devicons/fonts
  #
  # Sets JS compressor. No compression by default.
  # Possible variants: 'yui', 'uglifier', nil
  #
  js_compressor: ~
  #
  # Sets CSS compressor. No compression by default.
  # Possible variants: 'yui', 'sass', nil
  #
  css_compressor: ~
  #
  # Sets cachebusting policy for generated assets.
  #
  # Possible variants:
  #
  #   none - disables cachebusting
  #
  #     source file:  _assets/javascripts/app.css
  #     output file:  _site/assets/javascriptis/app.css
  #     output URL:   /assets/javascripts/app.css
  #
  #   soft - leave filenames as-is, but `?cb=<md5>` suffix for URLs generated
  #          with `asset_path`, `javascript` and `stylesheet`:
  #
  #     source file:  _assets/javascripts/app.css
  #     output file:  _site/assets/javascriptis/app.css
  #     output URL:   /assets/javascripts/app.css?cb=4f41243847da693a4f356c0486114bc6
  #
  #   hard - (default) injects cachebusting checksum into processed filename:
  #
  #     source file:  _assets/javascripts/app.css
  #     output file:  _site/assets/javascriptis/app-4f41243847da693a4f356c0486114bc6.css
  #     output URL:   /assets/javascripts/app-4f41243847da693a4f356c0486114bc6.css
  #
  cachebust: hard
  #
  # Whenever or not cache compiled assets (disabled by default).
  # See `Compilation Cache` section of README for details.
  #
  cache: false
  #
  # Specifies list of MIME types that needs to have gzipped versions.
  # You can set it to `false` to disable gzipping. Only javascripts and
  # stylesheets are gzipped by default.
  #
  gzip: [ text/css, application/javascript ]
  #
  # Does not concatenates files requested by `javascript` and `stylesheet`
  # helpers. Instead outputs multiple files in order they are required.
  # Default: false
  #
  debug: true
  #
  # Configuration version. Used to force cache invalidation.
  # Default: 1
  #
  version: 1
